In [2]:
import numpy as np
even_number = np.arange(2,21,2)
print(even_number)

[ 2  4  6  8 10 12 14 16 18 20]


In [5]:
space_number = np.linspace(0,1,5)
print(space_number)

[0.   0.25 0.5  0.75 1.  ]


In [7]:
full_array = np.full((3,3),7)
print(full_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [8]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
random = np.random.rand(10)
print(random)

[0.71308073 0.1798348  0.42918645 0.79624438 0.40393222 0.32562067
 0.36627542 0.55446999 0.26813386 0.74181372]


In [31]:
ori_array = np.arange(1,13)
reArray = ori_array.reshape(3,4)
print(reArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
print(reArray.shape)
print(reArray.ndim)

(3, 4)
2


In [32]:
original_array = np.arange(1,26)
reshape_Array = original_array.reshape(5,5)
print(reshape_Array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [24]:
first_row = reshape_Array[0,:]
print(first_row)

[1 2 3 4 5]


In [28]:
last_column = reshape_Array[:,-1]
print(last_column)

[ 5 10 15 20 25]


In [29]:
reshape_Array[reshape_Array > 15] = 0
print(reshape_Array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
